manifest:
  remotes:
  - name: zmkfirmware
    url-base: https://github.com/zmkfirmware
  - name: urob
    url-base: https://github.com/urob
  - name: zmk-driver-azoteq-iqs5xx
    url-base: https://github.com/danielnordqvist
  projects:
  - name: zmk
    remote: urob
    revision: main
    import: app/west.yml
  - name: zmk-helpers
    remote: urob
    revision: main
  - name: zmk-driver-azoteq-iqs5xx
    remote: danielnordqvist
    revision: main
